### ISSUE TITLE
Blog Post

### ISSUE THREAD

**Issue by patflynn** [transparency-dev/trillian-tessera#11]

**Comment by tracymiranda** [comment]
Draft for review here: https://docs.google.com/document/d/1fxabrSx4IsHS3P__k43oZsEWGhUUQde-u_1zsMY3U_0/edit

**Comment by tracymiranda** [comment]
@patflynn I've made major updates and this is now ready for a review, comments, etc: https://docs.google.com/document/d/1A7OIWgevmizmvSXVDIk4JTdq137bGY_bg__8RkyuF7o/edit#heading=h.iqqvcxjanlp4

@AlCutter the performance data section could do with some serious input, please take a look. Plus of course rest of the content is all open to change as we see fit. 

@roger2hk @mhutchinson @phbnf please review and comment on alpha blog post shared above 🙏
