### ISSUE TITLE
Tessera needs to support CT tile/data path

### ISSUE THREAD

**Issue by phbnf** [transparency-dev/trillian-tessera#171]
`static-ct-api` entry bundles are stored under `tile/data`: https://github.com/C2SP/C2SP/blob/main/static-ct-api.md#log-entries. This is different from the tiles specs, where entry bundles are stored under `tile/entries`. Josie had a go at trying to align both https://github.com/C2SP/C2SP/issues/94, and it seems unlikely that they will converge.

I'm thinking of adding an option to tessera setting this path. Having said that, I can't think of a use case different than CT, so we might as not make this option accessible outside of CT. I can be explicit with names that this should on be used for CT, but maybe you can think of a better way of doing it?

**Comment by AlCutter** [comment]
Ah, right.

Yes, let me have a chew on this - I'd very much prefer to avoid having an option here which would allow non-Static-CT-API implementations to fiddle with this path.
