### ISSUE TITLE
[PersonalityKit] Provide a simple sync-add wrapper

### ISSUE THREAD

**Issue by AlCutter** [transparency-dev/trillian-tessera#193]
Some personalities want to delay returning from calls to their `Add` API until the provided entry is integrated into the tree (e.g. Sigstore does this currently).

Tessera's `Add` function returns as soon as an index is durably assigned to the entry, but it does not guarantee that the entry has been integrated at that point (although it _should_ be integrated within seconds).

A simple wrapper which can be used to "decorate" Tessera's `Add` API could monitor the growth of the log (e.g. by watching `checkpoint`), and block until the observed log size is larger than the durably assigned index.

**Comment by mhutchinson** [comment]
Note that #182 converts the main `Add()` method to return futures. We should consider returning a future from this mixin if appropriate.
