### ISSUE TITLE
Replace SCTFE multi-config with flags for a single log

### ISSUE THREAD

**Issue by phbnf** [transparency-dev/trillian-tessera#200]
Towards #88 

Today, the SCTFE is configured via a config proto file, and supports multiple logs. We've decided to drop the support for multiple logs, and move to flags.

I'll do this in multiple steps along these lines:
 1. drop multi log support
 2. move from config to flags where we can, keep some things in there if need be, especially for keys that will undergo further changes
 3. on GCP, use KMS and/or Tink
 4. simplify the internals of the SCTFE to remove the virtual configs structs, if we can

**Comment by patflynn** [comment]
makes a ton of sense to minimize the surface for the MVP.

**Comment by phbnf** [comment]
The config is now gone. A bit more work is required here to simplify the internals, and pass keys in a better way.

**Comment by phbnf** [comment]
Closing this issue as we're migrating SCTFE code to transparency-dev/static-ct.

Here are issues for the two outstanding items:
 - https://github.com/transparency-dev/static-ct/issues/5
 - https://github.com/transparency-dev/static-ct/issues/6
