### ISSUE TITLE
[Deduplication] look at extracting deduplication logic from sequencer queue into mixin

### ISSUE THREAD

**Issue by mhutchinson** [transparency-dev/trillian-tessera#331]
We still have some logic in the internal queue used for sequencing that performs some deduplication: https://github.com/transparency-dev/trillian-tessera/blob/main/storage/internal/queue.go#L102

This is a bit of a funny situation as it's very internal to Tessera, and not easily controllable by users. It also has some peculiarities because it only dedupes within an in-memory batch. This means the following code could lead to 1 or 2 entries being in the log, depending on whether a batch was flushed in between the calls:

```
s.Add(x)
s.Add(x)
```

Take a look at pulling out this deduplication into a mixin similar to the `Awaiter`. This will let personalities have more control over how this works, and Tessera will have less code, and be more predictable.

**Comment by roger2hk** [comment]
Is this one the same idea as the personality level deduplication plug-in/add-on?
