### ISSUE TITLE
[GCP Conformance] reduce prerequisites in terraform to create service accounts

### ISSUE THREAD

**Issue by mhutchinson** [transparency-dev/trillian-tessera#339]
The terraform script should create whatever accounts and roles are needed. The prereqs should be as minimal as possible:
 - set up a GCP account (with billing? or is free tier enough?)
 - be able to authenticate as a project admin

https://github.com/transparency-dev/trillian-tessera/tree/main/deployment/live/gcp/conformance

**Comment by roger2hk** [comment]
I wondered if we can have an optional IAM module, so we can always choose to skip if that's not needed.

**Comment by mhutchinson** [comment]
> I wondered if we can have an optional IAM module, so we can always choose to skip if that's not needed.

I'll see whether that's needed as I write this out. For the distributor I just created the iam accounts and roles in the main module with no conditionality and it worked fine:

https://github.com/transparency-dev/distributor/blob/main/deployment/modules/distributor/main.tf#L156

There could be a reason that this is different though.

**Comment by AlCutter** [comment]
Fixed by #347
