### ISSUE TITLE
MySQL full tiles are not immutable

### ISSUE THREAD

**Issue by cmurphy** [transparency-dev/trillian-tessera#364]
The Merkle tree and entries APIs for the MySQL and POSIX conformance examples behave differently, and I think the MySQL one violates the [spec](https://github.com/C2SP/C2SP/blob/main/tlog-tiles.md) ("This endpoint is immutable, so its caching headers SHOULD be long-lived.").

For each personality, I created 280 entries, so the second level 0 tile should be a partial tile with 24 entries:

```
$ for i in `seq 1 280` ; do curl -d "[${i}]" -H "Content-Type: application/data" -X POST ${WRITE_URL}add & done ; wait
```

For POSIX, the second full tile is not accessible yet:

```
$ curl -s ${READ_URL}tile/0/001 -o - 
404 page not found
```

Only the partial tile corresponding to the log size is available:

```
$ curl -i -s ${READ_URL}tile/0/001.p/24 
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 768
Content-Type: application/octet-stream
Last-Modified: Tue, 03 Dec 2024 22:17:40 GMT
Date: Tue, 03 Dec 2024 22:36:57 GMT
```

For MySQL, the second full tile is always accessible:

```
$ curl -i -s ${READ_URL}tile/0/001 
HTTP/1.1 200 OK
Cache-Control: public, max-age=31536000, immutable
Date: Tue, 03 Dec 2024 22:37:46 GMT
Content-Length: 832
Content-Type: application/octet-stream
```

And it changes when I add new entries:

```
$ curl -s ${READ_URL}tile/0/001 -o - | sha256sum
47fde106d1f8dfe199a5a8a15b386a383d7293abc80adbd8edea11a0de1ae4d6  -
$ curl -d 'new entry 1' -H "Content-Type: application/data" -X POST ${WRITE_URL}add
280
$ curl -s ${READ_URL}tile/0/001 -o - | sha256sum
3f92a25712ae6a310522017f2aeeca00d96965efcd9ea66ea5b166d951395299  -
```

It's also curious that the `W` value doesn't matter at all when accessing partial tiles in MySQL:

```
$ curl -s ${READ_URL}tile/0/001.p/1 -o - | sha256sum
3f92a25712ae6a310522017f2aeeca00d96965efcd9ea66ea5b166d951395299  -
$ curl -s ${READ_URL}tile/0/001.p/24 -o - | sha256sum
3f92a25712ae6a310522017f2aeeca00d96965efcd9ea66ea5b166d951395299  -
```

but that at least is not inconsistent with the spec, just possibly a surprising difference for clients developing against it.

**Comment by mhutchinson** [comment]
Looks like something funny happened in #281 where an `impliedTreeSize` was calculated and passed into a method that was always expecting that parameter to be the optional tile width. I don't know that this is the root cause of this bug, but it ain't right. @roger2hk and I will take a look at this today.

**Comment by AlCutter** [comment]
@mhutchinson Reopening as I think there's still an issue - essentially the same bug still exists but for fetching entry bundles at the head of the tree:

```
❯ curl http://localhost:2024/checkpoint
transparency.dev/tessera/example
5
crhLo94gM4hl/8HFxxlfgDghS98EypJd0pRA/joq/lI=

— transparency.dev/tessera/example rjMOFUIpOk/p6U7izjvthDAh4BLmFIXyx5YW9pDFnfr2WklF+2PkyeJusodsqPnxaO/WoMeuijarebelb+6e9dNYTgo=

# yay:
❯ curl http://localhost:2024/tile/0/000 -i
HTTP/1.1 404 Not Found
Date: Fri, 06 Dec 2024 14:59:24 GMT
Content-Length: 0

# Oh noes :
❯ curl http://localhost:2024/tile/entries/000 -i
HTTP/1.1 200 OK
Date: Fri, 06 Dec 2024 15:01:09 GMT
Content-Type: application/octet-stream
Transfer-Encoding: chunked

...
```

**Comment by mhutchinson** [comment]
Good to have this tracked but the severity is less. In the PR that closed the originally reported issue you'll find I left a strategic comment saying to not add the caching headers.
