### ISSUE TITLE
[AWS] codelab terragrunt destroy doesn't appear to work

### ISSUE THREAD

**Issue by AlCutter** [transparency-dev/trillian-tessera#395]
**Description**

Having finished playing with my AWS codelab instance, I wanted to turn it down and release resources, so I ran `terragrunt destroy` from the `deployment/live/aws/codelab` directory.

The result was ... nothing happened. The command just hangs with no output.

Running `terragrunt plan` or `terragrunt apply` from the same directory got me a bunch of output saying that everything was hunky dory and that resources matched config, so whatever it is appears only to affect the `destroy` command.

I noticed that if I hit <return> the hanging command does exit after a little while.

**Comment by roger2hk** [comment]
Both @phbnf and I encountered the same problem. The interactive yes/no was hidden in the DEBUG output for some reason. That's why it just hanged without any output.

The current workaround is to execute `terragrunt destroy --terragrunt-log-level debug --terragrunt-debug`.

**Comment by AlCutter** [comment]
That'd explain it :)
Probably worth adding that command to the `aws/codelab/README.md` until it gets fixed upstream (presumably?)

**Comment by phbnf** [comment]
Yeah that's what I told you about the other day, (and what led me to discover the oddity of GCP terraform popping up in some debug logs when I execute the AWS terraform).

I have observed this behaviour on some VM I created, not all of them. Interesting that you also see it. I wonder whether this is a Terragrunt issue... Set "TF_LOG=trace", and the output appear. Can you check if that works for you?

**Comment by phbnf** [comment]
> Probably worth adding that command to the aws/codelab/README.md until it gets fixed upstream

I specifically removed instructions explaining how to turn down resources, and invite folks to delete their account to avoid any further cost. That's what the GCP instructions say as well. I can add instructions back if you'd like, but I'd put warning tape around it.

Running Terragrunt destroy is not enough to get rid of all the resources: the terraform S3 bucket and Dynamodb tables will stay around for instance. The only way for me to know with certainty that running Terragrunt destroy + deleting the bucket + Dynamodb table is enough to get rid of everything, is to wait for a month and see what's billed at the end. Until then, the best recommendation we can give is to delete the account.

**Comment by AlCutter** [comment]
I feel like we should put _something_ in the docs about it; it seems likely that other folks are going to step on this rake too, given we know it's there we should at least warn them about it.

The driver in my case was that while I knew that the doc says to destroy the project/account/whatever, given how laborious the process to do all the AWS click-ops stuff to set it up is, I wanted to `terraform destroy` to minimise costs while hedging against having to spin it all up again to check some random change in the near future. 

If the doc can be made to warn that while this might seem like a good idea, it isn't going to work as well as one might expect it to (and on multiple fronts, to boot), then the nudge to do the delete thing will be more likely to land.
