### ISSUE TITLE
Tessera needs to support CT Static API

### ISSUE THREAD

**Issue by mhutchinson** [transparency-dev/trillian-tessera#41]
This spec has some significant differences from the tlog-tiles spec that need to be supported by Tessera: https://github.com/C2SP/C2SP/blob/main/static-ct-api.md

The most significant of these is that entry bundles need to support interleaving of data that is not committed to by the Merkle tree.

I think we should think quite hard about how we want to support this. The DRY principle says that we should have a single implementation that can support extra data in addition to normal data, but it's worth considering whether some amount of duplication allows us to keep support for non-verifiable data out of the core of a library for implementing verifiable data structures.

**Comment by AlCutter** [comment]
I think this is done, so closing for now.
