### ISSUE TITLE
Multi-implementation Repo structure and build finalized

### ISSUE THREAD

**Issue by patflynn** [transparency-dev/trillian-tessera#5]
Not sure if this issue should exist or not. I'm using it as a placeholder for answering the question of how would an implementation start adding code to this repo. 

Questions like:

- [ ] what folder does it go into?
- [ ] how do I hook into repo's build?
- [ ] where does the sample personality go?

**Comment by mhutchinson** [comment]
Is there any more to do on this? I think we're happy with the current shape of the repo.

**Comment by mhutchinson** [comment]
I flagged this because it's marked as `done` in the planning stuff on the right hand side, but it's still open.
