### ISSUE TITLE
CI setup for GCP

### ISSUE THREAD

**Issue by patflynn** [transparency-dev/trillian-tessera#7]

**Comment by mhutchinson** [comment]
I added a basic CI integration for the MySQL implementation in #142. This demonstrates that running the conformance tool against binaries in CI is possible to do, and I agree with the comment above that the work of setting up CI is better tracked per-storage implementation. If there is more work to support CI that is needed by all implementations then let's create more specific issues to track?

**Comment by mhutchinson** [comment]
This was "CI setups", but to be clearer about the scope of work we still have left, I've repurposed this to be scoped to GCP. We have a bunch of CI stuff set up for POSIX and MySQL. The remaining work is integrating with a non-GH action runner and tying the success/failure back into GH in an actionable way.

@AlCutter - added you as a co-asignee as we're in this together.
