### ISSUE TITLE
CT static API personality

### ISSUE THREAD

**Issue by phbnf** [transparency-dev/trillian-tessera#88]
Implements https://c2sp.org/static-ct-api

Pieces of work:
- [ ] port certificate-transparency-go CTFE to this repo, removing all the things we don't need anymore, and connect it to GCP Tessera to write tiles (no checkpoint at this stage)
  - [x] break ground with an initial port
  - [x] move more things over to drop dependency on non X509/TLS stuff from `github.com/google/certificate-transparency-go` (for instance `github.com/google/certificate-transparency-go/trillian/util`, `github.com/google/certificate-transparency-go/trillian/testdata`)
  - [ ] double check that tiles and leaf are compliant with https://c2sp.org/static-ct-api
    - [x] Fix Data Type
    - [x] Store fingerprints chain in leaves 
  - [ ] have a look through all the old TODOs I ported over
  - [x] move over handlers_test.go
  - [x] add README and/or docker config to generate proto and mocks
- [x] add a signer option
- [x] design+build a chain storage service (see what we can re-use from Roger's recent work on certificate-transparengy-go CTFE): see #132
- [ ] design+build deduplication: ongoing
- [x] design+modify configuration pipeline if need be: we've decided to stick to flags
- [x] quota system: we've decided not rely on Tessera's pushbacks to start with. We'll add a quota system later if needed. See #186 
- [ ] decide how we handle errors, and which one we pass to clients
- [x] migrate codebase to a different repo
- [ ] load test with real world CT data
- [ ] deployment instructions

**Comment by mhutchinson** [comment]
What's the difference between this issue and #41 ?

**Comment by AlCutter** [comment]
I think #41 is Tessera APIs which _enable_ a CT Static API personality to be built, and this one is the task of actually building such a personality.

**Comment by phbnf** [comment]
I'm going to close this issue to migrate it under https://github.com/transparency-dev/static-ct, where the SCTFE now lives.

**Comment by phbnf** [comment]
https://github.com/transparency-dev/static-ct/issues/10
