### ISSUE TITLE
User Docs

### ISSUE THREAD

**Issue by patflynn** [transparency-dev/trillian-tessera#9]
For Alpha we want to at a minimum:

- [ ] Provide clear introduction to Tessera why it exists and what it's for
- [ ] Provide a smooth guided walkthrough for the Alpha Call-To-Action 
- [x] Provide examples with some docs
- [x] Codelab? Can we leverage Go's example code docs support

**Comment by mhutchinson** [comment]
I think a reasonable exit criteria for this is if a developer with basic knowledge of what a transparency log is (but doesn't necessarily understand tiles) can come to the main [Tessera Go Docs](https://pkg.go.dev/github.com/transparency-dev/trillian-tessera) and perform the following actions:
 - deploy an example personality and interact with it
 - view the code and understand how the example personality works
 - write their own personality

**Comment by roger2hk** [comment]
The godoc examples do not work as expected for some reason.

https://pkg.go.dev/github.com/transparency-dev/trillian-tessera@v0.0.0-20240924095918-964eff9a81cb/api/layout

<img width="1311" alt="image" src="https://github.com/user-attachments/assets/363867cf-4b7e-447d-9c1a-8e64473f59c7">

**Comment by mhutchinson** [comment]
It could be that it needs to pull all of Tessera and its deps in order to build that, and it runs out of time?

**Comment by roger2hk** [comment]
> It could be that it needs to pull all of Tessera and its deps in order to build that, and it runs out of time?

I believe so. The Go playground build timeout is 10 seconds.

**Comment by mhutchinson** [comment]
Discussed with Al and we think the criteria in my comment above have been met. Any other improvements will come as part of getting developers through the existing docs.
